export const COLUMN_ERROR_MESSAGES = {
  NOT_FOUND: 'COLUMN_NOT_FOUND',
  TO_COLUMN_NOT_FOUND: 'TO_COLUMN_NOT_FOUND',
  FROM_COLUMN_NOT_FOUND: 'FROM_COLUMN_NOT_FOUND',
  POSITION_IS_BIGGER_THAN_COLUMNS: 'POSITION_IS_BIGGER_THAN_COLUMNS',
};

export const TASK_ERROR_MESSAGES = {
  NOT_FOUND: 'TASK_NOT_FOUND',
};

export const KAMBAN_ERROR_MESSAGES = {
  NOT_FOUND: 'KAMBAN_NOT_FOUND',
};
